[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['account-abstraction/=lib/account-abstraction/contracts/']
solc_version = '0.8.19'
bytecode_hash = "none"
cbor_metadata = false
optimize = true
runs = 1000000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
