[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.21'
bytecode_hash = "none"
cbor_metadata = false
optimize = true
via-ir = true
runs = 1000000
ffi = true
[fuzz]
runs = 1024

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
